### ISSUE TITLE
When using SSO and getSSOData, if I use popup, I need to implement popup & redirect

### ISSUE THREAD

**Issue by mgonto** [auth0/widget#72]
It's not cool that if I want to use `getSSOData` to handle SSO, I have to use Redirect and Popup for it if I need popup for Login. SSO should work with both cases out of the box.

**Comment by rkralston** [comment]
Basically, if I am using the Lock widget popup for authentication and I turn on SSO, I should not have to change my application code. Conceivably, I may need to add the flag `sso: true` to the lock.show() call.

As it stands now, if I have been using the lock component, I have to drastically change my login in order to get SSO to work.

SSO should work with the Lock widget out of the box.

**Comment by woloski** [comment]
@rkralston This widget is deprecated. Please use auth0/lock for any question
